services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=mydb
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p1234", "ping", "-h", "localhost"]
      interval: 1s
      retries: 20
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 5001:5001
    depends_on:
      db:
       condition: service_healthy
    restart: always
volumes:
   dbdata:
